#!/usr/bin/env bash
#
# Generate app configuration in JSON format.

set -Eeuo pipefail

# Read app name from generated fly.toml.
app="$(sed 's|^app = "*\(.*\)"$|\1|gp;d' <fly.toml)"

# Read IPv4 address.
addr="$(flyctl ips list --json | \
    jq --raw-output '.[] | select(.Type == "v4") | .Address')"

# Generate both ports in one go to make sure they are not equal.
ports="$(shuf -i 1024-65535 -n 2)"
or_port="$(echo "${ports}" | head -n1)"
pt_port="$(echo "${ports}" | tail -n1)"

jq --null-input \
    --arg app "${app}" \
    --arg addr "${addr}" \
    --argjson or_port "${or_port}" \
    --argjson pt_port "${pt_port}" \
    '{email: "your@email.here", app: $app, addr: $addr, or_port: $or_port, pt_port: $pt_port}'
