#!/usr/bin/env bash
#
# Generate fly.toml for a new app and deploy Snowflake.

set -Eeuo pipefail

# REGION is optional. See `flyctl platform regions` for the full list.
export region="${REGION:-fra}"

# fly.toml should not exist.
if [[ -a 'fly.toml' ]]; then
    echo 'ERROR: fly.toml already exists.'
    exit 1
fi

# Generate random app name.
export app="snowflake-$(tr -dc '0-9a-z' </dev/urandom | dd bs=8 count=1 2>/dev/null)"
echo "If something goes wrong, run 'flyctl apps destroy ${app}' and start again."
echo

# Create app, allocate IP address, create volume.
flyctl launch --name "${app}" --region "${region}" --image thetorproject/snowflake-proxy:latest --no-deploy
config="${app}-fly.toml"
mv fly.toml "${config}"
flyctl ips allocate-v4 --config "${config}"
flyctl volumes create fly_obfs4 --region "${region}" --size 1 --config "${config}"

# References:
# https://community.torproject.org/relay/setup/snowflake/standalone/
cat <<EOF >"${config}"
app = "${app}"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "thetorproject/snowflake-proxy:latest"
EOF

# Deploy
flyctl deploy --config "${config}"
echo
echo "CONFIG=${config}"
